name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: pip install -e '.[dev]'

      - name: Run quality checks
        run: ./check.sh

      - name: Run core tests (CI-safe)
        run: |
          echo "=== Running deterministic test suite ==="
          pytest -q --maxfail=2 --disable-warnings -m "not introspection" --cov=axiom --cov-report=term-missing --cov-report=xml

      - name: Upload coverage artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml

      - name: Run introspection tests (optional)
        if: always()
        run: |
          echo "=== Checking for local model files ==="
          if [ -d "models" ] && ls models/*.gguf >/dev/null 2>&1; then
            echo "Models found. Running introspection suite..."
            pytest -q --disable-warnings -m introspection || true
          else
            echo "No models found. Skipping introspection tests."
          fi

      - name: Upload introspection results
        if: always() && !cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: introspection-results-${{ matrix.python-version }}
          path: |
            .pytest_cache/
            **/introspection_results.txt
            tests/__pycache__/
          if-no-files-found: ignore
