name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # Use the official, built-in caching for pip/uv. It's more efficient.
          cache: 'pip'

      - name: Install dependencies from lockfile
        run: |
          pip install uv
          # This is the correct command to use the lockfile for a reproducible build
          uv pip sync . --extra dev

      - name: Run quality checks
        run: ./check.sh

      - name: Run tests
        run: pytest -q --cov=axiom --cov-report=term-missing --cov-report=xml

      - name: Upload coverage artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml